---
- name: Converge
  become: true
  hosts: all
  pre_tasks:
    - ansible.builtin.apt: update_cache=true cache_valid_time=600
      name: Update apt cache.
      when: ansible_os_family == 'Debian'
  roles:
    - role: buluma.packer
