---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Check packer version
      ansible.builtin.command:
        cmd: "{{ packer_bin_path }}/packer --version"
      changed_when: false
